{% set version = '1.2.1' %}

package:
  name: cnapy
  version: {{ version }}

source:
  url: https://github.com/cnapy-org/cnapy/archive/v{{ version }}.tar.gz
  sha256: 2640eada9d0b21bc68090e7d72c73f29709b57fd67bff5f28632d7a8177e5cfc

build:
  noarch: python
  number: 0  # NOTE: increment for new build/set to zero for new version
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  channels:
    - cnapy
    - Gurobi
    - IBMDecisionOptimization
  build:
    - setuptools
    - python >=3.7,<3.11
  run:
    - python >=3.7,<3.11
    - numpy =1.23
    - scipy =1.12
    - optlang
    - cobra >=0.29
    - sympy >=1.12
    - appdirs >=1.4
    - matplotlib >=3.6
    - requests >=2.28
    - efmtool_link >=0.0.7
    - optlang_enumerator >=0.0.12 
    - straindesign >=1.12
    - qtpy >=2.3
    - pyqtwebengine >=5.15 
    - qtconsole =5.4
    - gurobipy >=11.0
    - cplex >=22.1
    - openpyxl
    
test:
  imports:
    - cnapy

about:
  home:  https://github.com/cnapy-org/cnapy
  license: Apache-2.0
  license_family: MIT
  license_file: LICENSE
  summary: Enumeration of multiple solutions to a MILP with the optlang framework.
  doc_url: https://github.com/cnapy-org/cnapy
  dev_url: https://github.com/cnapy-org/cnapy

extra:
  recipe-maintainers:
    - axelvonkamp
